# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import pentagram.models


class Migration(migrations.Migration):

    dependencies = [
        ('pentagram', '0004_auto_20160714_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='counter_line',
            new_name='counter_like',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(null=True, upload_to=pentagram.models.photos_directory),
        ),
    ]
